# **Array Creation & Shape**

In [2]:
import numpy as np

**np.array() - Create an array from a Python list**

In [ ]:
# 1D array (vector)
x = np.array([1, 2, 3, 4])
print(x)

[1 2 3 4]


- A feature vector

- A weight vector

- A single data sample

In [ ]:
# 2D array (matrix)
X = np.array([[1, 2, 3],
              [4, 5, 6]])
print(X)

[[1 2 3]
 [4 5 6]]


- Rows = samples

- Columns = features

**np.zeros() - Create an array full of zeros**

In [ ]:
# Vector of zeros
w = np.zeros(5)
print(w)

[0. 0. 0. 0. 0.]


- Initial weight vector

- Gradient storage

In [ ]:
# Matrix of zeros
W = np.zeros((3, 4))
print(W)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**np.ones() - Create an array full of ones**

In [ ]:
b = np.ones(3)
print(b)

[1. 1. 1.]


- Bias terms

- Normalisation baselines

In [ ]:
# 2D version
B = np.ones((2, 3))
print(B)

[[1. 1. 1.]
 [1. 1. 1.]]


**np.empty() - Allocate memory without filling values**

In [ ]:
A = np.empty((2, 3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


Values are random garbage in memory. Used for fast performance.

- High-performance simulations

- When you overwrite values immediately

**np.arange() - Like Python range, but for arrays**

In [ ]:
t = np.arange(0, 10)
print(t)

[0 1 2 3 4 5 6 7 8 9]


- Index arrays

- Time steps

- Numeric sequences

In [ ]:
x = np.arange(0, 10, 2) # 2 step size
print(x)

[0 2 4 6 8]


**np.linspace() - Evenly spaced numbers**

In [ ]:
x = np.linspace(0, 1, 5)
print(x)

[0.   0.25 0.5  0.75 1.  ]


When you want exact number of points. important for plotting & ML

- Activation function plots

- Loss curves

- Continuous simulations



**np.reshape() - Change shape without changing data**

In [3]:
x = np.array([1, 2, 3, 4, 5, 6])
X = x.reshape((2, 3))
print(X)

[[1 2 3]
 [4 5 6]]


Converted a 1D vector into a 2×3 matrix

- CNN inputs

- Batch formatting

- Feature matrices

**np.ravel() - Flatten array into 1D**

In [4]:
X = np.array([[1, 2, 3],
              [4, 5, 6]])

v = X.ravel()
print(v)

[1 2 3 4 5 6]


when converting:

- Images to vectors

- Feature maps to classifiers

**np.shape - Get dimensions of an array**

In [5]:
X = np.array([[1, 2, 3],
              [4, 5, 6]])

print(X.shape)

(2, 3)


**np.size - Total number of elements**

In [6]:
print(np.size(X))

6


- Loss averaging

- Data validation

#### 90% of bugs in ML come from wrong array shapes, not from wrong math. **use np.shape**