In [1]:
import numpy as np

**np.min() and np.max() - Find range**

In [2]:
x = np.array([10, 20, 50, 80])

print(np.min(x))
print(np.max(x))

10
80


In [3]:
X = np.array([[1, 200],
              [2, 300],
              [3, 400]])

print(np.min(X, axis=0))
print(np.max(X, axis=0))

[  1 200]
[  3 400]


**np.ptp() - Peak-to-Peak (range)**

In [4]:
x = np.array([10, 20, 50, 80])
print(np.ptp(x))

70


In [5]:
max(x) - min(x)

np.int64(70)

**Min–Max Normalisation**

In [6]:
x = np.array([10, 20, 50, 80])

x_norm = (x - np.min(x)) / np.ptp(x)
print(x_norm)

[0.         0.14285714 0.57142857 1.        ]


**np.percentile() - Robust statistics**

In [7]:
x = np.array([10, 12, 15, 18, 100])

print(np.percentile(x, 50))  # median
print(np.percentile(x, 90))

15.0
67.20000000000002


**np.round(), np.floor(), np.ceil()**

In [8]:
x = np.array([1.2, 2.5, 3.7])
print(np.round(x))

[1. 2. 4.]


In [9]:
print(np.floor(x))

[1. 2. 3.]


In [10]:
print(np.ceil(x))

[2. 3. 4.]


**np.vstack() - np.hstack()**

In [14]:
# Vertical stack - add samples
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6]])

X = np.vstack((A, B))
print(X)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
# Horizontal stack - add features
y = np.array([[10],
              [20],
              [30]])

X_new = np.hstack((X, y))
print(X_new)

[[ 1  2 10]
 [ 3  4 20]
 [ 5  6 30]]


**np.concatenate()**

In [16]:
X = np.concatenate((A, B), axis=0)

**Standardisation**

In [17]:
# (Mean = 0, Std = 1)
x = np.array([10, 20, 30, 40])

x_std = (x - np.mean(x)) / np.std(x)
print(x_std)

[-1.34164079 -0.4472136   0.4472136   1.34164079]
