In [1]:
import numpy as np

**Basic Indexing**

In [2]:
# 1D array indexing

x = np.array([10, 20, 30, 40, 50])

print(x[0])   # first element
print(x[2])   # third element
print(x[-1])  # last element

10
30
50


In [5]:
# 2D array indexing
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(X[0, 1])   # row 0, column 1

2


**Slicing**

In [6]:
# 1D slicing
x = np.array([10, 20, 30, 40, 50])

print(x[1:4])

[20 30 40]


In [7]:
# 2D slicing
print(X[:, 1])     # all rows, column 1
print(X[0:2, :])   # first two rows, all columns

[2 5 8]
[[1 2 3]
 [4 5 6]]


Used in ML:

- Select features
- Remove bias column
- Split data

**Boolean Masking**

Masking used in filter data by condition.

In [8]:
x = np.array([5, 12, 7, 20, 3])

mask = x > 10
print(mask)

[False  True False  True False]


In [9]:
print(x[mask])

[12 20]


**Filtering a Dataset**

In [10]:
X = np.array([[25, 30000],
              [40, 50000],
              [22, 20000],
              [35, 45000]])

# Select people older than 30
filtered = X[X[:, 0] > 30]
print(filtered)

[[   40 50000]
 [   35 45000]]


**np.where() - Conditional selection**

In [11]:
x = np.array([1, 4, 7, 10])

result = np.where(x > 5, 1, 0)
print(result)

[0 0 1 1]


Used in:

- Creating labels

- Thresholding predictions

In [12]:
# Replace values conditionally
x = np.array([1, -2, 3, -4])

x_fixed = np.where(x < 0, 0, x)
print(x_fixed)

[1 0 3 0]


**np.argmax() and np.argmin()**

In [13]:
probs = np.array([0.1, 0.6, 0.3])

predicted_class = np.argmax(probs)
print(predicted_class)

1


Used in classification.

- Used in classification
- Softmax output

**np.argsort() - Sorting by index**

In [14]:
scores = np.array([88, 92, 79, 95])

sorted_indices = np.argsort(scores)
print(sorted_indices)

[2 0 1 3]


Used in:

- Ranking

- Top-k selection

**np.unique() - Unique values**

In [15]:
labels = np.array([1, 2, 1, 3, 2, 1])

print(np.unique(labels))

[1 2 3]


Used in:

- Class detection

- Dataset inspection

**Handling Missing and Invalid Values**

In [16]:
x = np.array([1.0, np.nan, 2.0])

print(np.isnan(x))

[False  True False]


In [17]:
# Filter out NaNs
print(x[~np.isnan(x)])

[1. 2.]


In [18]:
# np.isinf()
x = np.array([1.0, np.inf, 2.0])

print(np.isinf(x))

[False  True False]


**np.clip() - Limit values**

In [19]:
x = np.array([-10, 0, 5, 20])

x_clipped = np.clip(x, 0, 10)
print(x_clipped)

[ 0  0  5 10]


Used in:

- Gradient clipping

- Preventing exploding values