In [7]:
import numpy as np

**Vectors and Matrices**

In [8]:
# 1D Vector
x = np.array([1, 2, 3])
print(x)

[1 2 3]


Used in ML; A feature vector, A weight vector, A gradient

In [9]:
# 2D Matrix
X = np.array([[1, 2, 3],
              [4, 5, 6]])
print(X)

[[1 2 3]
 [4 5 6]]


In ML; Rows as samples, Columns as features

In [10]:
# Shape
print(X.shape)

(2, 3)


**Transpose — np.transpose() or .T**

In [11]:
# Transpose swaps rows and columns.
X_T = X.T
print(X_T)

[[1 4]
 [2 5]
 [3 6]]


Used in ML for:

- Normal equations
- Gradient computation
- Covariance matrices

**Dot Product & Matrix Multiplication**

In [12]:
# Vector dot product
x = np.array([1, 2, 3])
w = np.array([0.1, 0.2, 0.3])

y = np.dot(x, w)
print(y)

1.4


Mathematically:

$ y= x^Tw$

In [13]:
# Matrix × Vector (Linear model)
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])

y_hat = X @ w
print(y_hat)

[2.5 4.  5.5]


$\hat{y} = Xw$

In [14]:
# Matrix × Matrix (Neural network layers)
W1 = np.array([[0.2, 0.3],
               [0.4, 0.5]])

W2 = np.array([[1.0],
               [2.0]])

Z = W1 @ W2
print(Z)

[[0.8]
 [1.4]]


**Identity Matrix — np.eye()**

In [15]:
# Identity matrix = matrix version of number 1

I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Property

A @ I == A

Used in ML; Regularisation, Numerical stability

**Matrix Inverse — np.linalg.inv()**

In [16]:
A = np.array([[4, 7],
              [2, 6]])

A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [17]:
# Check
print(A @ A_inv)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


Output ≈ Identity matrix.

Used in closed-form linear regression:

$w = (X^T X)^{-1} X^T y$

**Determinant — np.linalg.det()**

In [18]:
A = np.array([[1, 2],
              [3, 4]])

print(np.linalg.det(A))

-2.0000000000000004


Used in ML:

- Check if matrix is invertible
- Detect degenerate systems

If determinant = 0 means **no inverse**

**Norms — np.linalg.norm()**

Norm = vector length (magnitude).

In [20]:
# L2 norm (Euclidean)
x = np.array([3, 4])
print(np.linalg.norm(x))

5.0


Used in ML:

- Regularisation (L2)
- Distance metrics
- Gradient magnitude

**Eigenvalues & Eigenvectors — np.linalg.eig()**

In [23]:
A = np.array([[2, 0],
              [0, 3]])

values, vectors = np.linalg.eig(A)

print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)

Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


Used in ML:

- PCA
- Spectral clustering
- Stability analysis

**Singular Value Decomposition (SVD) — np.linalg.svd()**

In [24]:
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

U, S, Vt = np.linalg.svd(X)

print("U:\n", U)
print("S:\n", S)
print("Vt:\n", Vt)

U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S:
 [9.52551809 0.51430058]
Vt:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


Used in ML:

- PCA
- Dimensionality reduction
- Latent semantic analysis (NLP)

**Diagonal Matrix — np.diag()**

In [26]:
v = np.array([1, 2, 3])
D = np.diag(v)
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


Used in ML:

- Covariance matrices
- Weight decay
- Spectral methods

**Example**

In [27]:
# Data
X = np.array([[1, 1],
              [1, 2],
              [1, 3]])  # bias term included

y = np.array([1, 2, 3])

# Normal Equation
w = np.linalg.inv(X.T @ X) @ X.T @ y

print("Weights:", w)

Weights: [-1.77635684e-15  1.00000000e+00]


Check Later

- Activation Functions (Sigmoid, ReLU, Softmax) with NumPy

- Gradient Descent from scratch using NumPy