In [1]:
import numpy as np

**Vectors and Matrices**

In [2]:
# 1D Vector
x = np.array([1, 2, 3])
print(x)

[1 2 3]


Used in ML; A feature vector, A weight vector, A gradient

In [3]:
# 2D Matrix
X = np.array([[1, 2, 3],
              [4, 5, 6]])
print(X)

[[1 2 3]
 [4 5 6]]


In ML; Rows as samples, Columns as features

In [4]:
# Shape
print(X.shape)

(2, 3)


**Transpose — np.transpose() or .T**

In [5]:
# Transpose swaps rows and columns.
X_T = X.T
print(X_T)

[[1 4]
 [2 5]
 [3 6]]


Used in ML for:

- Normal equations
- Gradient computation
- Covariance matrices

**Dot Product & Matrix Multiplication**

In [6]:
# Vector dot product
x = np.array([1, 2, 3])
w = np.array([0.1, 0.2, 0.3])

y = np.dot(x, w)
print(y)

1.4


Mathematically:

$ y= x^Tw$

In [8]:
# Matrix × Vector (Linear model)
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])

y_hat = X @ w
print(y_hat)

[2.5 4.  5.5]


$\hat{y} = Xw$

In [9]:
# Matrix × Matrix (Neural network layers)
W1 = np.array([[0.2, 0.3],
               [0.4, 0.5]])

W2 = np.array([[1.0],
               [2.0]])

Z = W1 @ W2
print(Z)

[[0.8]
 [1.4]]


**Identity Matrix — np.eye()**

In [10]:
# Identity matrix = matrix version of number 1

I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Property

A @ I == A

Used in ML; Regularisation, Numerical stability