# Mathematical Operations

In [2]:
import numpy as np

**np.add, np.subtract, np.multiply, np.divide - element-wise operations**

In [3]:
# Element-wise addition
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

c = np.add(a, b)
print(c)

[11 22 33]


In [4]:
# Element-wise subtraction
c = np.subtract(b, a)
print(c)

[ 9 18 27]


In [6]:
# Element-wise multiplication
# This is NOT matrix multiplication. It is element-by-element
c = np.multiply(a, b)
print(c)

[10 40 90]


In [7]:
# Element-wise division
c = np.divide(b, a)
print(c)

[10. 10. 10.]


Used in ML for:

- Feature scaling

- Normalisation

- Gradient updates

**np.dot() and np.matmul() — Matrix Multiplication**

In [9]:
# Dot product of vectors
x = np.array([1, 2, 3])
w = np.array([0.1, 0.2, 0.3])

y = np.dot(x, w)
print(y)

1.4


This computes $y= x_{1}w_{1} + x_{2}w_{2} + x_{3}w_{3}$. Used in; Logistic regression, Perceptrons, Linear regression

In [10]:
# Matrix × Vector
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

w = np.array([0.1, 0.2])

y = np.dot(X, w)
print(y)

[0.5 1.1 1.7]


In [11]:
# Matrix × Matrix
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.matmul(A, B)
print(C)

[[19 22]
 [43 50]]


**This is exactly how;** Neural network layers work, Feature transformations happen.

**np.exp() and np.log() — Exponential & Log**

In [16]:
# Exponential
x = np.array([0, 1, 2])
y = np.exp(x)
print(y)

[1.         2.71828183 7.3890561 ]


**Used in ML Losses**, Softmax, Sigmoid, Probabilities

In [15]:
# Logarithm
x = np.array([1, 2.718, 7.389])
y = np.log(x)
print(y)

[0.         0.99989632 1.99999241]


**Used in;** Cross-entropy loss, Log-likelihood

**np.sqrt() and np.power() — Roots & Powers**

In [17]:
# Square root
x = np.array([1, 4, 9, 16])
y = np.sqrt(x)
print(y)

[1. 2. 3. 4.]


**Used in;** Distance metrics, Standard deviation, Optimisation algorithms

In [18]:
# Power
x = np.array([1, 2, 3])
y = np.power(x, 2)
print(y)

[1 4 9]


**Used in;** Mean squared error, Regularisation (L2)

**np.abs() — Absolute Value**

In [19]:
x = np.array([-3, -1, 0, 2])
y = np.abs(x)
print(y)

[3 1 0 2]


**Used in;** L1 regularisation, Error magnitude

**np.sum(), np.mean(), np.std(), np.var()**

These are statistical operations, used in:

- Feature normalisation

- Loss averaging

- Batch statistics

In [20]:
# Sum
x = np.array([1, 2, 3, 4])
print(np.sum(x))

10


In [21]:
# Mean
print(np.mean(x))

2.5


In [22]:
# Standard Deviation
print(np.std(x))

1.118033988749895


In [23]:
# Variance
print(np.var(x))


1.25


In [25]:
# In matrix, axis argument is Crucial
X = np.array([[1, 2, 3],
              [4, 5, 6]])

print(np.mean(X, axis=0))  # column-wise / across samples
print(np.mean(X, axis=1))  # row-wise / across features

[2.5 3.5 4.5]
[2. 5.]


**Real Machine Learning Example (Forward + Loss)**

1 step of linear regression

In [26]:
# Data: 4 samples, 2 features
X = np.array([[1, 2],
              [2, 3],
              [3, 4],
              [4, 5]])

# Weights
w = np.array([0.1, 0.2])

# Predictions
y_hat = np.dot(X, w)

# True labels
y = np.array([1, 2, 3, 4])

# Mean Squared Error
loss = np.mean(np.power(y_hat - y, 2))

print("Predictions:", y_hat)
print("Loss:", loss)

Predictions: [0.5 0.8 1.1 1.4]
Loss: 3.015
